name: DOCS to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docs/zebra-ui-docs/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        working-directory: docs/zebra-ui-docs
      - name: Build Nuxt project
        run: npx nuxt build --preset github_pages
        working-directory: docs/zebra-ui-docs
      - name: Deploy for Gitee 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs/zebra-ui-docs/.output/public
          # enable single-commit to reduce the repo size
          single-commit: true
          clean: true
