name: Upload Files to Server

on:
  push:
    branches:
      - master
    paths:
      - docs/zebra-ui-docs/**

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
        working-directory: docs/zebra-ui-docs

      - name: Build Site
        run: pnpm run build
        working-directory: docs/zebra-ui-docs

      - name: Upload File via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'docs/zebra-ui-docs/.output'
          target: '/www/wwwroot/zebraui-docs/'

      - name: Install SSH Pass
        run: sudo apt-get install -y sshpass

      - name: Deploy with Docker
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /www/wwwroot/zebraui-docs/docs/zebra-ui-docs"
